# tombi: format.rules.table-keys-order = "version-sort"

[".config/bat/themes"]
refreshPeriod = "168h"
type = "git-repo"
url = "https://github.com/catppuccin/bat.git"

[".config/ghostty/themes"]
exact = true
include = [ "*/themes/**" ]
refreshPeriod = "168h"
stripComponents = 2
type = "archive"
url = "https://github.com/catppuccin/ghostty/archive/refs/heads/main.zip"

[".config/tmux/plugins/catppuccin/tmux"]
refreshPeriod = "168h"
type = "git-repo"
url = "https://github.com/catppuccin/tmux.git"
