# tombi: format.rules.table-keys-order = "version-sort"

[".config/bat/themes"]
refreshPeriod = "168h"
type = "git-repo"
url = "https://github.com/catppuccin/bat.git"

[".config/ghostty/themes"]
include = [ "*/themes/**" ]
refreshPeriod = "168h"
stripComponents = 2
type = "archive"
url = "https://github.com/catppuccin/ghostty/archive/refs/heads/main.zip"

[".config/tmux/plugins/catppuccin/tmux"]
refreshPeriod = "168h"
type = "git-repo"
url = "https://github.com/catppuccin/tmux.git"

["Library/Application Support/Godot/text_editor_themes"]
include = [ "*/themes/**" ]
refreshPeriod = "168h"
stripComponents = 2
type = "archive"
url = "https://github.com/catppuccin/godot/archive/refs/heads/main.zip"

["Library/Developer/Xcode/UserData/FontAndColorThemes"]
include = [ "*/themes/**" ]
refreshPeriod = "168h"
stripComponents = 2
type = "archive"
url = "https://github.com/catppuccin/xcode/archive/refs/heads/main.zip"
