# # https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices#how-do-i-use-shell-integration
# set-option -g allow-passthrough on
#
# # https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices#i-want-to-see-tmux-window-titles-as-tabwindow-titles-in-iterm2
# set-option -g set-titles on
# set-option -g set-titles-string '#T'

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_window_status_style "rounded"

# https://github.com/catppuccin/tmux
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
