[tools]
"cargo:beancount-language-server" = "latest"
"cargo:jinja-lsp" = "latest"
"github:artempyanykh/marksman" = "latest"
"github:clangd/clangd" = "latest"
"github:errata-ai/vale" = "latest"
"github:latex-lsp/texlab" = "latest"
"github:redhat-developer/vscode-xml" = "latest"
"github:ryanoasis/nerd-fonts" = { version = "latest", asset_pattern = "FontPatcher.zip", bin_path = ".", postinstall = "sed -i '' '1s/python$/python3/' $MISE_TOOL_INSTALL_PATH/font-patcher" }
"go:github.com/sqls-server/sqls" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
hadolint = "latest"
lua-language-server = "latest"
node = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@olrtg/emmet-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:awk-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:fixjson" = "latest"
"npm:htmlhint" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:sql-formatter" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
oxfmt = "latest"
oxlint = "latest"
"pipx:basedpyright" = "latest"
"pipx:djlint" = "latest"
"pipx:ruff" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:tombi" = "latest"
"pipx:yamlfix" = "latest"
rust-analyzer = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
taplo = "latest"
yamlfmt = "latest"
yamllint = "latest"

[settings]
lockfile = true
