# tombi: format.rules.table-keys-order = "version-sort"

fix = true
target-version = "py314"  # Always generate Python 3.14-compatible code.

[format]
docstring-code-format = true  # Enable reformatting of code snippets in docstrings.
skip-magic-trailing-comma = true

[lint.flake8-annotations]
allow-star-arg-any = true
ignore-fully-untyped = true
