# tombi: format.rules.table-keys-order = "ascending"

"$schema" = "https://starship.rs/config-schema.json"
add_newline = false

[c]
symbol = "🥐"

# tombi: format.rules.table-keys-order = "ascending"
[character]
error_symbol = "[>](bold red)"
success_symbol = "[>](bold green)"

[container]
symbol = "🏺"

# tombi: format.rules.table-keys-order = "ascending"
[cpp]
disabled = false
symbol = "🥐"

[directory]
read_only = "🔏"

[docker_context]
symbol = "🐳"

[fill]
symbol = ""

[gcloud]
symbol = "☁️"

[git_branch]
symbol = "🌵"

# tombi: format.rules.table-keys-order = "ascending"
[git_status]
ahead = "^"
behind = "v"
conflicted = "x"
deleted = "-"
diverged = "%"
modified = "*"
renamed = ">"
staged = "+"
stashed = "$"
typechanged = "<"
untracked = "?"
up_to_date = "."

[golang]
symbol = "🐹"

[gradle]
symbol = "🐘"

[java]
symbol = "☕️"

[jobs]
symbol = "✳️"

# tombi: format.rules.table-keys-order = "ascending"
[lua]
lua_binary = "luajit"
symbol = "🌕"

[nodejs]
symbol = "🟩"

[package]
symbol = "📦"

[python]
symbol = "🐍"

[rlang]
symbol = "📐"

[rust]
symbol = "🦀"

# tombi: format.rules.table-keys-order = "ascending"
[shlvl]
disabled = false
symbol = "🎚️"
